name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - release/**
  pull_request:
    branches:
      - main
      - master
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
    - name: Get source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        ini-values: post_max_size=256M, max_execution_time=180
    - run: sudo pear list
    - run: sudo pear channel-update pear.php.net
    - run: sudo pear upgrade --force pear/pear
    - run: sudo pear list
    - run: sudo pear install --force package.xml
    - run: sudo pear list
    - run: sudo pear package
    - run: sudo pear package-validate
    - run: sudo pear install --force *.tgz
    - run: sudo pear list
    # Prepare fonts (see https://askubuntu.com/a/25614)
    - run: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    - run: sudo apt install -y ttf-mscorefonts-installer
    - run: sudo cp -rp /usr/share/fonts/truetype/msttcorefonts/verdana.ttf Image/Canvas/Fonts/
    - run: sudo cp -rp /usr/share/fonts/truetype/msttcorefonts/verdanab.ttf Image/Canvas/Fonts/
    - run: sudo cp -rp /usr/share/fonts/truetype/msttcorefonts/verdanai.ttf Image/Canvas/Fonts/
    - run: sudo cp -rp /usr/share/fonts/truetype/msttcorefonts/verdanaz.ttf Image/Canvas/Fonts/
    # Install pre-requisites and run test scripts
    - run: composer install
    - run: php tests/gradients.php > gradients.png
    - run: php tests/imagemap.php > imagemap.html
    - run: php tests/png.php
    - run: php tests/jpg.php
    # - run: php tests/ps.php
    # - run:php tests/pdf.php
    - run: php tests/svg.php
    - run: php tests/text.php > text.png
    - run: php tests/lineends.php > lineends.png
